apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: unique-id-service
spec:
  template:
    spec:
      containers:
        - image: arnavb25/media-microservice
          imagePullPolicy: "Always"
          env:
            - name: IS_KN
              value: "knative"
          command: ["UniqueIdService"]
          ports:
            - name: h2c
              containerPort: 80
      name: unique-id-service
